// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSLQat1V1-8CYdyKNsYmptoNJRE3lbd8c',
    appId: '1:54966662865:web:3be65247b219dd2540f7f0',
    messagingSenderId: '54966662865',
    projectId: 'lecturadiariaapp',
    authDomain: 'lecturadiariaapp.firebaseapp.com',
    storageBucket: 'lecturadiariaapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACo4u7gdKKysPZgphLLOE3o7E9EslUYQ0',
    appId: '1:54966662865:android:22203554f6df1cc240f7f0',
    messagingSenderId: '54966662865',
    projectId: 'lecturadiariaapp',
    storageBucket: 'lecturadiariaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPUTxCZbbuv58Su9WmlBl0WYnVFZxzj4E',
    appId: '1:54966662865:ios:60db0dc8685ad91240f7f0',
    messagingSenderId: '54966662865',
    projectId: 'lecturadiariaapp',
    storageBucket: 'lecturadiariaapp.firebasestorage.app',
    iosClientId: '54966662865-3ud38mcggcstnk5jtl5vkqfgp2udtens.apps.googleusercontent.com',
    iosBundleId: 'com.example.fronted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPUTxCZbbuv58Su9WmlBl0WYnVFZxzj4E',
    appId: '1:54966662865:ios:60db0dc8685ad91240f7f0',
    messagingSenderId: '54966662865',
    projectId: 'lecturadiariaapp',
    storageBucket: 'lecturadiariaapp.firebasestorage.app',
    iosClientId: '54966662865-3ud38mcggcstnk5jtl5vkqfgp2udtens.apps.googleusercontent.com',
    iosBundleId: 'com.example.fronted',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSLQat1V1-8CYdyKNsYmptoNJRE3lbd8c',
    appId: '1:54966662865:web:074d11fa8f4b322140f7f0',
    messagingSenderId: '54966662865',
    projectId: 'lecturadiariaapp',
    authDomain: 'lecturadiariaapp.firebaseapp.com',
    storageBucket: 'lecturadiariaapp.firebasestorage.app',
  );
}
