name: Auto Move Issues and PRs

on:
  issues:
    types: [opened, assigned, closed]
  pull_request:
    types: [opened, closed]

jobs:
  move_project:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar GitHub CLI
        run: sudo apt update && sudo apt install gh -y

      - name: Autenticar en GitHub CLI
        run: gh auth login --with-token ${{ secrets.GITHUB_TOKEN }} --hostname github.com

      - name: Mover Issue a "Backlog" cuando se cree
        if: github.event_name == 'issues' && github.event.action == 'opened'
        run: gh project item-add --project 2 --issue $(jq --raw-output .issue.number "$GITHUB_EVENT_PATH") --status "Backlog"

      - name: Mover Issue a "In progress" cuando se asigne
        if: github.event_name == 'issues' && github.event.action == 'assigned'
        run: gh project item-add --project 2 --issue $(jq --raw-output .issue.number "$GITHUB_EVENT_PATH") --status "In progress"


      - name: Mover PR a "Under review" cuando se abra
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: gh project item-add --project 2 --issue $(jq --raw-output .issue.number "$GITHUB_EVENT_PATH") --status "Under review"


      - name: Mover PR a "Done" cuando se fusione
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: gh project item-add --project 2 --issue $(jq --raw-output .issue.number "$GITHUB_EVENT_PATH") --status "Done"

